# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-03 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='none', max_length=30, verbose_name='标题')),
                ('blog_category', models.CharField(blank=True, max_length=50, verbose_name='标签')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='修改时间')),
                ('blog_content', models.TextField(blank=True, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'get_latest_by': 'Time',
            },
        ),
        migrations.CreateModel(
            name='comment_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='none', max_length=100, verbose_name='评论的内容')),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=10, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('answer', models.CharField(max_length=50, verbose_name='密保问题')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='comment_blog',
            name='blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='目标博客', to='lll.user'),
        ),
        migrations.AddField(
            model_name='comment_blog',
            name='comment_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='评论的人', to='lll.user'),
        ),
        migrations.AddField(
            model_name='blog_user',
            name='blog_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='发博文的人', to='lll.user'),
        ),
    ]
